blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns =\
[
    url(r'^$', views.mainpage, name='mainpage'),
    url(r'^blog/$', views.ArticleListView.as_view(), name='blog'),
    url(r'^blog/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name="detail"),
    url(r'^blog/search/$', views.search, name='search'),

]

musicplayer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.musicplayer, name='index'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^music/', include('musicplayer.urls')),
    url(r'^', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
#coding=utf-8
from django.db import models
from django.utils import timezone

class Tag(models.Model):
    name = models.CharField(max_length=200)
    def __unicode__(self):
        return self.name


class Article(models.Model):
    #author = models.ForeignKey('auth.User')
    author = models.CharField(max_length=50, default='踢叉叉')
    title = models.CharField(max_length=200, default='无标题')
    tags = models.ManyToManyField(Tag, blank=True)
    text = models.TextField("正文")
    published_date = models.DateTimeField("发布时间", auto_now_add=True)
    last_modified_date = models.DateTimeField('最后一次修改时间', auto_now=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def if_exist(self):
        article = Article.objects.filter(title=self.title)
        return bool(article)

    def __unicode__(self):
        return self.title

blog/views.py
#coding=utf8
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from django.views.generic import ListView,DetailView,View

from music_player import files 
from .models import Article,Tag
from .content_parser import convert_all


#import markdown2

class ArticleListView(ListView):
    model = Article
    ordering = ['author','-published_date',]
    template_name = "posts.html"
    context_object_name = "posts"
    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class ArticleDetailView(DetailView):
    model = Article
    template_name = "post.html"
    context_object_name = "post"
    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['zz'] = Tag.objects.all()
        return context

# def refresh(request):
#     convert_all(request.user)
#     return posts(request)

def mainpage(request):
    'render mainpage'
    articles = list(reversed(Article.objects.order_by('published_date')))
    musics = files.full_paths()

    import random
    music = random.choice(musics)

    context =\
    {
        'song_audio_file_url': music,
        'latest' : articles[0],
        'others' : articles[1:]
    }
    return render(request, 'main_page.html', context)


def search(request):
    q = request.GET.get('q', '')

    if q.startswith("GrandOrder:"):
        print q
        order = q[11:]
        print order
    return ArticleListView.as_view()(request)

blog/templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
{%load post_tags%}
<html>
<head>
<meta charset="utf-8">
<link rel="icon" href={% static 'pics/avatar.jpg' %}>
<title>Σ(っ ° Д °;)っ踢叉喵!!!∑(° Д° ノ)ノ </title>

<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

<style type="text/css">
body
{
    background-image:url({% static 'pics/background.jpg' %});
    background-repeat: no-repeat;
    background-position: middle;
    background-attachment: fixed;
    background-size: cover;
}
p{
	text-indent: 2em;
}
</style>
</head>

<body>
<div class="container" >
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h3 class="text-center">
				Σ(っ ° Д °;)っ 踢叉喵 !!!∑(° Д° ノ)ノ 
			</h3>
			<nav class="navbar navbar-default" role="navigation">				
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
					 <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"></span> 主页</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							 <a href="/blog/">文章</a>
						</li>
						<li>
							 <a href="/">主页走你X2</a>
						</li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">点一下啊<strong class="caret"></strong></a>
							<ul class="dropdown-menu">

								<li>
									 <a href="">点了也没用</a>
								</li>
								<li class="divider">
								</li>
								<li>
									 <a href="#">这是分割线下面的一个按钮</a>
								</li>
								<li class="divider">
								</li>
								<li>
									 <a href="#">这是又一个分割线下的又一个按钮</a>
								</li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-right" action="/blog/search/" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="反正你输啥进来都没用" value="喵喵喵" name="q"/>
						</div> 
						<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							 <a href="#">_!!!∑(° Д° ノ)ノ 啥！</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
{% block jumbotron %}

{% endblock %}

{% block text %}

{% endblock %}
</div>

<!--<div style="text-align:center">
    <audio id='musicplayer'controls autoplay>
        {% load staticfiles %}
        <source src="{% static 'musics/LaCampanella.mp3' %}" type="audio/mpeg">
    </audio>

</div>-->

<div class="container">
	<div >
		<a href="https://github.com/TX-QAQ">
			<img style="float:left" border="0" src="http://stackoverflow.com/users/flair/4804659.png" /><img style="float:right;clear:both;" border="0" src="{% static 'pics/github.png' %}" />
		</a>
	</div>
</div>

<script type="text/javascript" color="3,100,0" opacity="0.3" count="99" src="/media/js/canvas-nest.min.js"></script>
<script>
!function(){function o(w,v,i){return w.getAttribute(v)||i}function j(i){return document.getElementsByTagName(i)}function l(){var i=j("script"),w=i.length,v=i[w-1];return{l:w,z:o(v,"zIndex",-1),o:o(v,"opacity",0.5),c:o(v,"color","0,0,0"),n:o(v,"count",99)}}function k(){r=u.width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,n=u.height=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight}function b(){e.clearRect(0,0,r,n);var w=[f].concat(t);var x,v,A,B,z,y;t.forEach(function(i){i.x+=i.xa,i.y+=i.ya,i.xa*=i.x>r||i.x<0?-1:1,i.ya*=i.y>n||i.y<0?-1:1,e.fillRect(i.x-0.5,i.y-0.5,1,1);for(v=0;v<w.length;v++){x=w[v];if(i!==x&&null!==x.x&&null!==x.y){B=i.x-x.x,z=i.y-x.y,y=B*B+z*z;y<x.max&&(x===f&&y>=x.max/2&&(i.x-=0.03*B,i.y-=0.03*z),A=(x.max-y)/x.max,e.beginPath(),e.lineWidth=A/2,e.strokeStyle="rgba("+s.c+","+(A+0.2)+")",e.moveTo(i.x,i.y),e.lineTo(x.x,x.y),e.stroke())}}w.splice(w.indexOf(i),1)}),m(b)}var u=document.createElement("canvas"),s=l(),c="c_n"+s.l,e=u.getContext("2d"),r,n,m=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(i){window.setTimeout(i,1000/45)},a=Math.random,f={x:null,y:null,max:20000};u.id=c;u.style.cssText="position:fixed;top:0;left:0;z-index:"+s.z+";opacity:"+s.o;j("body")[0].appendChild(u);k(),window.onresize=k;window.onmousemove=function(i){i=i||window.event,f.x=i.clientX,f.y=i.clientY},window.onmouseout=function(){f.x=null,f.y=null};for(var t=[],p=0;s.n>p;p++){var h=a()*r,g=a()*n,q=2*a()-1,d=2*a()-1;t.push({x:h,y:g,xa:q,ya:d,max:6000})}setTimeout(function(){b()},100)}();
</script>
<script>
mp=document.getElementById("musicplayer");
function getVolume()
{
    alert(mp.volume);
}
function setHalfVolume()
{ 
    mp.volume=1;
}
setTimeout(setHalfVolume,0.1) 
function setFullVolume()
{ 
    mp.volume=1.0;
}
</script> 


</body>
</html>

blog/templates/main_page.html
{% extends "base.html" %}
{%load post_tags%}
{% block jumbotron %}

<div class="jumbotron">
	<h1 class="text-center">
		{{ latest.title }}
	</h1>
	<p>
		{{ latest.text|linebreaks }}
	</p>
	<p class="text-right">
			<a class="btn btn-primary btn-large" href="#">Learn more</a>
	</p>
</div>
{% endblock %}

{% block text %}

    {% for post in others %}
        <div class="col-md-3 column">
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|abstract|linebreaks }}</p>
            <p class="text-right">
			<a class="btn" href="{% url 'blog:detail' post.pk %}">Learn more</a>
	        </p>
        </div>
    {% endfor %}
<div class="col-md-12 column">
<div style="text-align:center">
    <audio id='musicplayer'controls autoplay>
        <!--{% load staticfiles %}-->		
		<source src="{%static '' %}{{song_audio_file_url}}" type="audio/mpeg">
    </audio>
</div>
</div>

{% endblock %}

blog/templates/post.html
{% extends "base.html" %}
{%load post_tags%}
{% block jumbotron %}
    <!--<a class="btn btn-primary btn-large" href="/blog/re">更新一下</a>-->

        <div class="jumbotron">
            <p class="text-right">发布于 {{ post.published_date }}</p>
            <h1 class="text-center"><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></h1>
            <div>分类:
                {% for item in zz %}
               	    <a class="btn btn-primary btn-large" href="">{{item.name}}</a>
                {% endfor %}
	        </div>
            <p>{{ post.text|linebreaks }}</p>


        </div>


{% endblock %}


{% block text %}

{% endblock %}

blog/templates/post_list.html
{% extends "base.html" %}
    <a class="btn btn-primary btn-large" href="/re">Learn more</a>
{% block jumbotron %}
    <a class="btn btn-primary btn-large" href="/blog/re">更新一下</a>
    {% for post in posts %}
        <div class="jumbotron">
            <p class="text-right">published at: {{ post.published_date }}</p>
            <h1 class="text-center"><a href="">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <p class="text-right">
			<a class="btn btn-primary btn-large" href="#">Learn more</a>
	        </p>
        </div>

    {% endfor %}
{% endblock %}


{% block text %}
    {% for post in posts %}
        <div class="jumbotron">
            <p class="text-right">published at: {{ post.published_date }}</p>
            <h1 class="text-center"><a href="">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <p class="text-right">
			<a class="btn btn-primary btn-large" href="#">Learn more</a>
	        </p>
        </div>

    {% endfor %}
			<a class="btn" href="#">Learn more1111111</a>
<div class="row clearfix">
				<a class="btn" href="#">Learn more222222</a>
    {% for post in posts %}
    <a class="btn" href="#">Learn more222222</a>
        <div class="col-md-4 column">
            <h2>
                Heading
            </h2>
            <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
            </p>
            <p>
                    <a class="btn" href="#">View details »</a>
            </p>
        </div>
    {% endfor %}
    {% for post in posts %}
        <div class="col-md-4 column">
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|linebreaksbr }}</p>
            <p class="text-right">
			<a class="btn" href="#">Learn more</a>
	        </p>
        </div>
    {% endfor %}
	<div class="col-md-4 column">
		<h2>
			Heading
		</h2>
		<p>
			Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
		</p>
		<p>
				<a class="btn" href="#">View details »</a>
		</p>
	</div>

{% endblock %}

blog/templates/posts.html
{% extends "base.html" %}
{%load post_tags%}
{% block jumbotron %}
    <a class="btn btn-primary btn-large" href="/blog/re">更新一下</a>
    {% for post in posts %}
        <div class="jumbotron">
            <p class="text-right">发布于 {{ post.published_date|date:"M d Y" }}</p>
            <h1 class="text-center"><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|abstract|linebreaks }}</p>
            
            <div class="text-right">
			<a class="btn btn-primary btn-large" href="{% url 'blog:detail' post.pk %}">Learn more</a>
	        </div>
            <p class="text-right">
			{{now}}
	        </p>
        </div>

    {% endfor %}
{% endblock %}


{% block text %}
{% endblock %}

musicplayer/templates/mainPage.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
<title>Σ(っ ° Д °;)っ踢叉喵!!!∑(° Д° ノ)ノ </title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->
<link rel="stylesheet" href="{% static 'css/musicplayer.css' %}">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<style type="text/css">
h2.pos_abs
{
    position:absolute;
    bottom:150px
}
p.thicker {font-weight: 9000}
</style>
<style>
body
{
    background-image:url("{%static 'pics/background.jpg'%}");
    background-repeat: no-repeat;
    background-position: middle;
    background-attachment: fixed;
    background-size: cover;
}

</style>
</head>


<!--<body background="{%static 'pics/background.jpg'%}">-->
<div class="page_header">
    <p class="thicker">
    <h1 style="text-align:center"><a href="">踢叉叉 喵喵喵喵喵</a></h1>
    <h1 style="text-align:center"><a href="">Σ(っ ° Д °;)っ踢叉喵!!!∑(° Д° ノ)ノ</a></h1>
    
    </p>
</div>


<h3 style="text-align:center;"><a href="/blog">Blogs,GO!</h3>







<h3 style="text-align:center"></h3>
<h3 style="text-align:center"></h3>
<h3 style="text-align:center"><a href="">龟が我が敌を喰らう</h3>
<h3 style="text-align:center"></h3>
<h3 style="text-align:center"></h3>
<h6 style="text-align:center"><a href="">竜神の剣を喰らえ</h6>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<p>背景图片是固定的。尝试向下滚动页面。</p>
<div style="text-align:center">
    <audio id='musicplayer'controls autoplay>
        {% load staticfiles %}
        <source src="{% static 'musics/LaCampanella.mp3' %}" type="audio/mpeg">
    </audio>

</div>


<div style="float:right;clear:both;">
<a href="https://github.com/TX-QAQ">
    <img border="0" src="{% static 'pics/github.png' %}" />
</a>
</div>



<script>
mp=document.getElementById("musicplayer");
function getVolume()
{
    alert(mp.volume);
}
function setHalfVolume()
{ 
    mp.volume=1;
}
setTimeout(setHalfVolume,0.1) 
function setFullVolume()
{ 
    mp.volume=1.0;
}
</script> 


</body>
</html>

musicplayer/templates/music.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>踢叉喵ヽ(✿ﾟ▽ﾟ)ノ</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
    <div>
        <h1><a href="">踢叉叉 喵喵喵喵喵</a></h1>

        <h3><a href="">龟神が我が敌を喰らう</h3>
        <h6><a href="">竜神の剣を喰らえ</h6>

    <div>
        <audio controls autoplay>
            {% load staticfiles %}
            <source src="{% static 'musics/LaCampanella.mp3' %}" type="audio/mpeg">
        </audio>
    </div>

</body>
</html>